#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/cltd.h"
#include "data-mov/leave.h"
#include "data-mov/movext.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/sub.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/setne.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "data-control/call.h"
#include "data-control/push.h"
#include "data-control/test.h"
#include "data-control/je.h"
#include "data-control/cmp.h"
#include "data-control/pop.h"
#include "data-control/ret.h"
#include "data-control/jmp.h"
#include "data-control/jbe.h"